services:
  - type: web
    name: mini-discord-backend
    env: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3
    startCommand: node scripts/createAdminInvite.js && node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGIN
        value: https://mini-discord-backend-07n7.onrender.com

  - type: web
    name: mini-discord-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_BASE
        value: https://mini-discord-backend.onrender.com
